### PR TITLE
Fix #155

### LINKED ISSUE #155: Bug with joined filesystem directory stream
[This line](https://github.com/QuiltMC/quilt-loader/blob/626490e6600d533d0c9f6be3d7a06bf1f489607a/src/main/java/org/quiltmc/loader/impl/filesystem/QuiltJoinedFileSystemProvider.java#L232) doesn't appear to check for the directory existing. This means that if one of the backing paths doesn't have the directory, a `NoSuchFileException` is thrown.

I discovered this whilst trying gametest on quilted fapi, this appears to be the cause of this error:
<details><summary>crashlog</summary>
<pre>
[12:18:08] [main/WARN] (ResourceAccess) getNamespaces in mod fabric-loot-tables-v1-testmod failed!
 java.nio.file.NoSuchFileException: /home/k/Documents/dev/quilted-fabric-api/deprecated/fabric-loot-tables-v1/build/classes/java/testmod/data
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:441) ~[?:?]
	at java.nio.file.Files.newDirectoryStream(Files.java:614) ~[?:?]
	at org.quiltmc.loader.impl.filesystem.QuiltJoinedFileSystemProvider$1.<init>(QuiltJoinedFileSystemProvider.java:228) ~[quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.filesystem.QuiltJoinedFileSystemProvider.newDirectoryStream(QuiltJoinedFileSystemProvider.java:215) ~[quilt-loader-0.17.6.jar:?]
	at java.nio.file.Files.newDirectoryStream(Files.java:614) ~[?:?]
	at org.quiltmc.qsl.resource.loader.impl.cache.ResourceAccess.getNamespaces(ResourceAccess.java:107) ~[resource_loader-3.0.0-beta.21+1.19.2.jar:?]
	at org.quiltmc.qsl.resource.loader.impl.ModNioResourcePack.getNamespaces(ModNioResourcePack.java:186) ~[resource_loader-3.0.0-beta.21+1.19.2.jar:?]
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.lambda$appendModResourcePacks$4(ResourceLoaderImpl.java:365) ~[resource_loader-3.0.0-beta.21+1.19.2.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at it.unimi.dsi.fastutil.objects.Reference2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Reference2ObjectOpenHashMap.java:1195) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Reference2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Reference2ObjectOpenHashMap.java:1179) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Reference2ObjectOpenHashMap$MapSpliterator.forEachRemaining(Reference2ObjectOpenHashMap.java:855) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Reference2ObjectOpenHashMap$ValueSpliterator.forEachRemaining(Reference2ObjectOpenHashMap.java:1179) ~[fastutil-8.5.6.jar:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.appendModResourcePacks(ResourceLoaderImpl.java:366) ~[resource_loader-3.0.0-beta.21+1.19.2.jar:?]
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.buildMinecraftResourcePack(ResourceLoaderImpl.java:377) ~[resource_loader-3.0.0-beta.21+1.19.2.jar:?]
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.buildMinecraftResourcePack(ResourceLoaderImpl.java:393) ~[resource_loader-3.0.0-beta.21+1.19.2.jar:?]
	at net.minecraft.resource.VanillaDataPackProvider.handler$zfp000$onPackGet(VanillaDataPackProvider.java:550) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.resource.VanillaDataPackProvider.method_14454(VanillaDataPackProvider.java:24) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.resource.ResourcePackProfile.of(ResourcePackProfile.java:35) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.resource.VanillaDataPackProvider.register(VanillaDataPackProvider.java:24) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.resource.ResourcePackManager.providePackProfiles(ResourcePackManager.java:44) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.resource.ResourcePackManager.scanPacks(ResourcePackManager.java:37) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.server.MinecraftServer.loadDataPacks(MinecraftServer.java:1322) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.server.SaveLoading$DataPacks.load(SaveLoading.java:59) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.server.SaveLoading.load(SaveLoading.java:22) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.server.SaveLoader.load(SaveLoader.java:18) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.test.TestServer.method_43615(TestServer.java:92) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.util.Util.waitAndApply(Util.java:952) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.util.Util.waitAndApply(Util.java:946) ~[minecraft-project-@-common-named.jar:?]
	at net.minecraft.test.TestServer.create(TestServer.java:90) ~[minecraft-project-@-common-named.jar:?]
	at net.fabricmc.fabric.impl.gametest.FabricGameTestHelper.lambda$runHeadlessServer$0(FabricGameTestHelper.java:67) ~[fabric-gametest-api-v1-4.0.0-beta.20+local-0.67.0-gametest-dev.jar:?]
	at net.minecraft.server.MinecraftServer.startServer(MinecraftServer.java:264) [minecraft-project-@-common-named.jar:?]
	at net.fabricmc.fabric.impl.gametest.FabricGameTestHelper.runHeadlessServer(FabricGameTestHelper.java:66) [fabric-gametest-api-v1-4.0.0-beta.20+local-0.67.0-gametest-dev.jar:?]
	at net.minecraft.server.Main.handler$zhd000$main(Main.java:2054) [minecraft-project-@-common-named.jar:?]
	at net.minecraft.server.Main.main(Main.java:147) [minecraft-project-@-common-named.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:24) [quilt-loader-0.17.6.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
</pre>
</details>

### PR DESCRIPTION
**Pull request by TheEpicBlock**
I went on a bit of a tangent with the testcase. At first I wrote the extra testcases. What I didn't realise at first that Quilt's memory fs *doesn't* throw `NoSuchFileException`, but the `UnixFileSystemProvider` *does* (and it seems like other platforms might too). So then I had to rewrite it again to include those in the tests.

This fixes the gametest issues in quilted fapi

### CODE REVIEW

File: src/main/java/org/quiltmc/loader/impl/filesystem/QuiltJoinedFileSystemProvider.java [hunk 1]
```diff
@@ -229,7 +229,7 @@ public DirectoryStream<Path> newDirectoryStream(Path dir, Filter<? super Path> f
 							return filter.accept(toJoinedPath(backing, path));
 						}));
 						anyReal = true;
-					} catch (NotDirectoryException e) {
+					} catch (NotDirectoryException | NoSuchFileException e) {
```
Comment (AlexIIL) [inline src/main/java/org/quiltmc/loader/impl/filesystem/QuiltJoinedFileSystemProvider.java]: Now that I'm looking at this it seems really odd to catch the exception - and not check `Files.isDirectory()` before invoking it?

I think the reason why this only caught `NotDirectoryException` before was because `Files.newDirectoryStream` names it explicitly - but I don't think it's a good idea to catch other exceptions too.

**Comment by AlexIIL** [comment]
Other than that - thanks for making this!
